# Generated by Django 5.2.5 on 2025-08-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepunch',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
